### ISSUE TITLE
Have some design for the rendered html.

### ISSUE THREAD

**Issue by soenkehahn** [soenkehahn/agora#49]
For this ticket this doesn't have to be fancy. But just *some* design, so that it doesn't look completely like a tech demo.

**Comment by casey** [comment]
I opened #52, which puts files in an unordered list. I don't think it closes this ticked, but it's a minor improvement. I wonder how good we can get it to look without resorting to CSS. Not that we *have* to avoid CSS, but using default-styled HTML elements can often produce quite readable pages.

**Comment by soenkehahn** [comment]
I think I would quickly resort to css. Which means that our server has to serve a css file. Which means we probably want a namespace for our files, e.g. `/files`.

**Comment by casey** [comment]
We should make `download` an icon (maybe a unicode character or emoji) so it's distinct from the file name.
